name: gtk-theme-pocillo
base: core24
version: '0.21.0'
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
summary: Pocillo GTK theme for GTK Snaps
description: |
  A snap that exports the Pocillo GTK theme.
grade: stable
confinement: strict

slots:
  gtk-2-themes:
    interface: content
    source:
      read:
        - $SNAP/share/gtk2/Pocillo
        - $SNAP/share/gtk2/Pocillo-dark
        - $SNAP/share/gtk2/Pocillo-light
        - $SNAP/share/gtk2/Pocillo-slim
        - $SNAP/share/gtk2/Pocillo-slim-dark
        - $SNAP/share/gtk2/Pocillo-slim-light
  gtk-3-themes:
    interface: content
    source:
      read:
        - $SNAP/share/themes/Pocillo
        - $SNAP/share/themes/Pocillo-dark
        - $SNAP/share/themes/Pocillo-light
        - $SNAP/share/themes/Pocillo-slim
        - $SNAP/share/themes/Pocillo-slim-dark
        - $SNAP/share/themes/Pocillo-slim-light
parts:
  gtk-2-themes:
    plugin: dump
    source: http://de.archive.ubuntu.com/ubuntu/pool/universe/b/budgie-artwork/ubuntu-budgie-themes_0.21.0_all.deb
    override-build: |
      snapcraftctl build
      pwd
      ls -l
      mkdir -p $CRAFT_PART_INSTALL/share/gtk2
      mv -f $CRAFT_PART_INSTALL/usr/share/themes/Pocillo* $CRAFT_PART_INSTALL/share/gtk2
    stage:
      - share/gtk2/*/gtk-2.0
  gtk-3-themes:
    plugin: dump
    source: http://de.archive.ubuntu.com/ubuntu/pool/universe/b/budgie-artwork/ubuntu-budgie-themes_0.21.0_all.deb
    override-build: |
      snapcraftctl build
      pwd
      ls -l
      mkdir -p $CRAFT_PART_INSTALL/share/themes
      mv -f $CRAFT_PART_INSTALL/usr/share/themes/Pocillo* $CRAFT_PART_INSTALL/share/themes
    stage:
      - share/themes/*/gtk-3.0
      - share/themes/*/gtk-4.0
