name: gtk-theme-pocillo
architectures:
  - all
version: '0.14.3.1'
summary: Pocillo GTK theme for GTK Snaps
description: |
  A snap that exports the Pocillo GTK theme.

base: bare
build-base: core20

grade: stable
confinement: strict

slots:
  gtk-2-themes:
    interface: content
    source:
      read:
        - $SNAP/share/gtk2/Pocillo
        - $SNAP/share/gtk2/Pocillo-slim
        - $SNAP/share/gtk2/Pocillo-dark
        - $SNAP/share/gtk2/Pocillo-dark-slim
        - $SNAP/share/gtk2/Pocillo-light
        - $SNAP/share/gtk2/Pocillo-light-slim
  gtk-3-themes:
    interface: content
    source:
      read:
        - $SNAP/share/themes/Pocillo
        - $SNAP/share/themes/Pocillo-slim
        - $SNAP/share/themes/Pocillo-dark
        - $SNAP/share/themes/Pocillo-dark-slim
        - $SNAP/share/themes/Pocillo-light
        - $SNAP/share/themes/Pocillo-light-slim
  content:
    allow-auto-connection:
      -
        plug-attributes:
          content: $SLOT(content)
        slot-attributes:
          content: gtk-2-themes
        slots-per-plug: "*"
      -
        plug-attributes:
          content: $SLOT(content)
        slot-attributes:
          content: gtk-3-themes
        slots-per-plug: "*"

parts:
     
  # Pocillo gtk theme
  #source: http://de.archive.ubuntu.com/ubuntu/pool/universe/b/budgie-artwork/ubuntu-budgie-themes_$SNAPCRAFT_PROJECT_VERSION_all.deb
    
  pocillo-gtk-theme:
    after: [utils]
    plugin: dump
    # we need to use a PPA as a base since snap cannot handle the deb compression format in the regular archive
    source: https://launchpad.net/~ubuntubudgie-dev/+archive/ubuntu/unstable-test/+files/ubuntu-budgie-themes_$SNAPCRAFT_PROJECT_VERSION_all.deb
    override-build: |
        snapcraftctl build
        mkdir -p $SNAPCRAFT_PART_INSTALL/share/themes
        mv $SNAPCRAFT_PART_INSTALL/usr/share/themes/Pocillo* $SNAPCRAFT_PART_INSTALL/share/themes/
        $SNAPCRAFT_STAGE/split-gtk-theme.sh $SNAPCRAFT_PART_INSTALL
    stage:
      - share/gtk2/*/gtk-2.0
      - share/themes/*/gtk-3*


  utils:
    plugin: dump
    source: utils
    prime:
      - -*
    build-packages:
      - try: [gtk-update-icon-cache]
      - else: [libgtk-3-bin]
